### ISSUE TITLE
PS4 Pro 5.1版本

### ISSUE THREAD

**Issue by shiki88** [Tilerphy/ps4broadcast#10]
emmmmm，http://192.168.1.150:26666/上显示的是LIVING STATUS: 1 channels.
另外PS4能上网，但是一直播就断线= =
twitch和b站也都无法正常显示，PS4用默认ip的情况下可以直播到twitch
PS4版本：PS4 Pro 5.1
ps4broadcast：1.4.3

**Comment by xiwei26** [comment]
你是不是也显示这个 
发生了错误
CE-33138-8
然后就断了？

**Comment by shiki88** [comment]
是的= =，也是这个错误

**Comment by Tilerphy** [comment]
@shiki88 @xiwei26 CE-33138-8指的确实是网络中断，我觉得我需要去看看你们的具体情况了，可以的话加我的qq，咱们远程协助来探察问题。 我的qq就是邮箱的数字部分。

**Comment by varequan** [comment]
我也遇到了相同的错误。是因为直播码失效了，重新开启直播后填好直播码，再在PS4上开始播送就可以了。

**Comment by Tilerphy** [comment]
@varequan 说的正确
