### ISSUE TITLE
如何自定义网关

### ISSUE THREAD

**Issue by EndangeredF1sh** [Tilerphy/ps4broadcast#23]
现网关均写死为192.168.200.1
看start-web.sh和install.sh多处存在本项配置 不敢轻举妄动修改
如何修改才能实现自定义网关到习惯的地址（如192.168.1.X）

**Comment by Tilerphy** [comment]
可以直接搜索192.168.200 然后replace成192.168.1  

但是你要确定和现有网段不冲突




| |
孙宗宝
邮箱：346410840@163.com
|

签名由 网易邮箱大师 定制

在2018年06月03日 02:08，EndangeredF1sh 写道：

现网关均写死为192.168.200.1
看start-web.sh和install.sh多处存在本项配置 不敢轻举妄动修改
如何修改才能实现自定义网关到习惯的地址（如192.168.1.X）

**Comment by EndangeredF1sh** [comment]
感谢指点
