### ISSUE TITLE
ps4 测速非常缓慢

### ISSUE THREAD

**Issue by LiuOcean** [Tilerphy/ps4broadcast#24]
带宽是足够的。 但是每次点分享，测速这个地方过不去，是因为设置不对吗？

**Comment by LiuOcean** [comment]
![image](https://user-images.githubusercontent.com/20659474/41158913-3995d9f4-6b5d-11e8-9fae-1a35892711ad.png)
![wechatimg348](https://user-images.githubusercontent.com/20659474/41159200-3fb34dfc-6b5e-11e8-9963-13f5c96a1af8.jpeg)
![wechatimg347](https://user-images.githubusercontent.com/20659474/41159208-4739cb78-6b5e-11e8-84c9-e75902aa7e26.jpeg)

**Comment by Tilerphy** [comment]
在ps4上你可能点错了，有一个“分享游玩过程” 不是把游戏分享给他人玩

**Comment by Tilerphy** [comment]
打开一个游戏，按share，左侧有个“分享游玩过程”

**Comment by Tilerphy** [comment]
然后出现Twitch Youtube 还有个什么的，三个，选twitch

**Comment by LiuOcean** [comment]
ojbk

**Comment by Tilerphy** [comment]
哈哈
