### ISSUE TITLE
下载了2.0 打开ip:26666 还是1.6.0 

### ISSUE THREAD

**Issue by ZEERDEER** [Tilerphy/ps4broadcast#26]
在百度云和 github分别都试过了0.0  

>
 当前版本（Current Version） v1.6.0.20180628

最新版本（Latest Version） v2.0.0.20180629（无法直接升级，请前往 https://github.com/Tilerphy/ps4broadcast/releases 下载最新版本）

**Comment by Tilerphy** [comment]
打开后界面能看到record path吗 能的话就是更新后的。不能的话等我回去更新吧




| |
孙宗宝
邮箱：346410840@163.com
|

签名由 网易邮箱大师 定制

在2018年07月13日 00:51，zeerdeer 写道：

在百度云和 github分别都试过了0.0

**Comment by zeerdeer** [comment]
谢谢
看的到
信息如图
↓↓↓↓
 [https://imgur.com/a/3TGe2UW](url)

**Comment by zeerdeer** [comment]
谢谢
看的到
信息如图
↓↓↓↓
 [https://imgur.com/a/3TGe2UW](url)

**Comment by Tilerphy** [comment]
看得到说明版本已经是2.0的了，可能是我的镜像里没有更新版本号。

**Comment by zeerdeer** [comment]
感谢更新2.0.1！
