### ISSUE TITLE
b站roomid

### ISSUE THREAD

**Issue by Lieqing** [Tilerphy/ps4broadcast#30]
我在网上找了几个方法 但是都没有用  显示的roomid都是0  请问大佬没有什么方法查看b站的roomid谢谢

**Comment by Tilerphy** [comment]
不是巨老资格的直播主roomid就是自己直播间链接最后的数字串




| |
孙宗宝
邮箱：346410840@163.com
|

签名由 网易邮箱大师 定制

在2018年08月04日 09:48，Lieqing 写道：

我在网上找了几个方法 但是都没有用 显示的roomid都是0 请问大佬没有什么方法查看b站的roomid谢谢

**Comment by Lieqing** [comment]
哦哦  谢谢
