### ISSUE TITLE
开始直播时出现CE-33138-8错误代码

### ISSUE THREAD

**Issue by AnitrateENN** [Tilerphy/ps4broadcast#34]
用电脑把SSR开分享给PS4，网络连接正常 也能够在PS4上看油管等，但是在设置完twitch的直播设置开始直播时右上角 on air 灰色 几秒后弹出错误代码   求问大佬是我设置不对还是什么 control pannel里的record path 没有填 是不是和这个有关？
更新 :应该是自己设置不对 不打开control pannel可以正常直播 一reset living就不行了。。。。
更新2 已经解决了  应该是自己的操作顺序不太对的原因

**Comment by Tilerphy** [comment]
非常感谢使用
