### ISSUE TITLE
本地录制的正确用法是什么？

### ISSUE THREAD

**Issue by EtherealAO** [Tilerphy/ps4broadcast#35]
在bilibili上推流了一会，ftp://虚拟机IP/records下什么都没出现[del]除了被封装在OVA里的ps4broadcast-2018-06-28(23:54:50).flv[/del]
虚拟机IP::26666下的record path设置成空和/records/都没有变化

**Comment by Tilerphy** [comment]
录像目录的权限需要被设置为任意读写，建议是执行一下 chmod 777 /records
