### ISSUE TITLE
26666页面正常访问，填写了B站推流信息，直播还是直接推到twitch了

### ISSUE THREAD

**Issue by twocold0451** [Tilerphy/ps4broadcast#41]
PS4 的IP必须是 192.168.200.X的吗，
我局域网内的ip都是 192.168.2.X的，所以ps4 我也设置成了2.x，是这个原因吗，
但我改成200.X后无法连接互联网

**Comment by Tilerphy** [comment]
虚拟机是创建了个虚拟网关，那个网段是200.x的，所以要用这个
