### ISSUE TITLE
大佬，b站直播弹幕不显示到留言板上了

### ISSUE THREAD

**Issue by beefjerky331** [Tilerphy/ps4broadcast#42]
RT，share里留言板功能也打开了

**Comment by Tilerphy** [comment]
B站现在更新了新的弹幕消息协议，新对弹幕进行了压缩。
目前来说可以通过重连房间的方式重回旧协议。
我尽快修改这个协议对接。

**Comment by beefjerky331** [comment]
> B站现在更新了新的弹幕消息协议，新对弹幕进行了压缩。
> 目前来说可以通过重连房间的方式重回旧协议。
> 我尽快修改这个协议对接。

感谢。

**Comment by daosanlan** [comment]
> B站现在更新了新的弹幕消息协议，新对弹幕进行了压缩。
> 目前来说可以通过重连房间的方式重回旧协议。
> 我尽快修改这个协议对接。

大佬，斗鱼弹幕也不能连接了，也是这个原因吗

**Comment by Tilerphy** [comment]
> 
> 
> > B站现在更新了新的弹幕消息协议，新对弹幕进行了压缩。
> > 目前来说可以通过重连房间的方式重回旧协议。
> > 我尽快修改这个协议对接。
> 
> 感谢。

Bilibili的弹幕协议已经修复。
点击26666那个控制页面的更新并重启，就可以了。

**Comment by Tilerphy** [comment]
> 
> 
> > B站现在更新了新的弹幕消息协议，新对弹幕进行了压缩。
> > 目前来说可以通过重连房间的方式重回旧协议。
> > 我尽快修改这个协议对接。
> 
> 大佬，斗鱼弹幕也不能连接了，也是这个原因吗

斗鱼的弹幕我倒是第一次听说，不过斗鱼的弹幕协议很好更改，我可以看一看

**Comment by daosanlan** [comment]
> > > B站现在更新了新的弹幕消息协议，新对弹幕进行了压缩。
> > > 目前来说可以通过重连房间的方式重回旧协议。
> > > 我尽快修改这个协议对接。
> > 
> > 
> > 感谢。
> 
> Bilibili的弹幕协议已经修复。
> 点击26666那个控制页面的更新并重启，就可以了。

好的谢谢!
