### ISSUE TITLE
没有直播画面

### ISSUE THREAD

**Issue by hibari333** [Tilerphy/ps4broadcast#5]
设置一路下来都正常，26666那个网页也能正确显示状态，但是直播间无画面，显示直播已断开，请重新刷新，但是我两端都重启了好几次。直播是哔哩哔哩，斗鱼没试。

**Comment by Tilerphy** [comment]
也许是bilibili提供的推流码已经过期，请申请新的bilibili推流码，填入控制台页面后，reset living

**Comment by Tilerphy** [comment]
另外bilibili给出的直播地址最后携带一个 /
请尝试去掉这个 / 重试。

最新版本已经修复 / 的问题。
