### ISSUE TITLE
能否改进一下Xbox兼容性

### ISSUE THREAD

**Issue by wwjjhh1995** [Tilerphy/ps4broadcast#53]
巨巨你好，
xbox的网络设置有些特殊，不能自己设置proxy，只能通过设置网关指向透明代理，借此科学上网。而且Xbox开启直播必须要开启twitch客户端，需要扶墙。
我目前网络情况，局域网中有一个架设了clash的旁路由，设置好iptables后，网关指向这个路由，Xbox可以借此上网。
之后我在这个旁路由上（debian系统）也安装了您的工具，但在start-web.sh中我看到您重写了iptables，因此脚本启动后我的Xbox借助网关代理上网会完全失效，也无法使用您的脚本成功转发流量。
不知道您的其他设置当中是否都将流量经过200.1转发。能否直接使用原生ip地址转发流量，这样可以与我的代理上网服务完全兼容。
以上，若打扰，望见谅。

**Comment by Tilerphy** [comment]
其实这个已经实现了，你看看start-web-ss.sh
