### ISSUE TITLE
拦截rtmp流到本服务，然后转发到国内平台

### ISSUE THREAD

**Issue by mickytmnew** [Tilerphy/ps4broadcast#57]
有没有办法ps5连接到路由器，路由器域名解析重定向，拦截rtmp流到本服务，转发到国内平台
PS5的其他服务依旧直联，也不影响加速器吧

想请教下是否可行，目前尚在研究源码，打算运行在本地docker中测试看看。
如有理解不正确的请指正，谢谢

**Comment by Tilerphy** [comment]
跨nat就办不到了，加速盒子都是路由，会多一层nat。
所以，
只需要这套程序和ps5同时在加速器下属的局域网就可以了。





---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年03月04日 20:44 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [Tilerphy/ps4broadcast] 拦截rtmp流到本服务，然后转发到国内平台 (Issue #57) |

有没有办法ps5连接到路由器，路由器域名解析重定向，拦截rtmp流到本服务，转发到国内平台
PS5的其他服务依旧直联，也不影响加速器吧

想请教下是否可行，目前尚在研究源码，打算运行在本地docker中测试看看。
如有理解不正确的请指正，谢谢

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
