### ISSUE TITLE
关于弹幕重定向的问题

### ISSUE THREAD

**Issue by mickytmnew** [Tilerphy/ps4broadcast#62]
关于twitch的弹幕和b站的弹幕，是相同的irc协议嘛？
如果是的话，是不是通过劫持irc.twitch.tv的方式，用四层转发就能直接解决呢？

非常抱歉，关于弹幕重定向的功能实现没看懂，恳请大佬指点。

**Comment by mickytmnew** [comment]
已经单独剥离了弹幕重定向功能，并打包docker
感谢代码分享

**Comment by lie5860** [comment]
> 已经单独剥离了弹幕重定向功能，并打包docker 感谢代码分享

大佬你怎么部署到docker的呀 有镜像吗~

**Comment by Tilerphy** [comment]
非常抱歉，最近工作较忙没及时看这里。
这里ps5向twitch的irc会发一个握手，后面就是单纯的接收twitch发来的irc消息了。

我这里是拦截了ps5发往twitch irc的消息，并伪造了握手过程。

b站的弹幕则是b站的自有协议，我是把弹幕姬项目代码进行了一些简化。




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年07月23日 12:09 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [Tilerphy/ps4broadcast] 关于弹幕重定向的问题 (Issue #62) |

关于twitch的弹幕和b站的弹幕，是相同的irc协议嘛？
如果是的话，是不是通过劫持irc.twitch.tv的方式，用四层转发就能直接解决呢？

非常抱歉，关于弹幕重定向的功能实现没看懂，恳请大佬指点。
