### ISSUE TITLE
ps5 bilibili无法显示弹幕

### ISSUE THREAD

**Issue by LinSHP** [Tilerphy/ps4broadcast#73]
我看代码是通过监听6667来和ps5交互的，我start之后，在ps5开启直播，可以在日志中看到两者的交互信息和心跳

我在直播间发送代码，可以在日志中看到弹幕的相关信息，但是ps5的游戏画面右下角始终没有任何相关的展示

想问下是ps5的协议变化了，还是啥，有啥排查的思路吗，因为上班，相关图片下班后补充，谢谢

**Comment by Tilerphy** [comment]
是b站的弹幕协议变了，因为b站协议不稳定，我就一直没修。现在都用手机看弹幕，不折腾那个内置弹幕了。



在 2024-11-05 10:56:11，"LinSP" ***@***.***> 写道：

我看代码是通过监听6667来和ps5交互的，我start之后，在ps5开启直播，可以在日志中看到两者的交互信息和心跳

我在直播间发送代码，可以在日志中看到弹幕的相关信息，但是ps5的游戏画面右下角始终没有任何相关的展示

想问下是ps5的协议变化了，还是啥，有啥排查的思路吗，因为上班，相关图片下班后补充，谢谢

**Comment by LinSHP** [comment]
电视玩的时候看手机弹幕还挺不方便，好的，我了解到ps的没变就行，b站弹幕我用了https://github.com/xfgryujk/blivedm/tree/dev
我晚上再试试

**Comment by Tilerphy** [comment]
有自己改库的能力就太好了。

好了借我抄抄。

哈哈哈哈哈哈哈










在 2024-11-05 16:13:11，"LinSP" ***@***.***> 写道：

电视玩的时候看手机弹幕还挺不方便，好的，我了解到ps的没变就行，b站弹幕我用了https://github.com/xfgryujk/blivedm/tree/dev
我晚上再试试
